# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timesTwo <- function(x) {
    .Call('_convReg_timesTwo', PACKAGE = 'convReg', x)
}

indicator <- function(x) {
    .Call('_convReg_indicator', PACKAGE = 'convReg', x)
}

Indicator <- function(xx) {
    .Call('_convReg_Indicator', PACKAGE = 'convReg', xx)
}

W <- function(lam, nu, sumTo) {
    .Call('_convReg_W', PACKAGE = 'convReg', lam, nu, sumTo)
}

Y <- function(lam, nu, sumTo) {
    .Call('_convReg_Y', PACKAGE = 'convReg', lam, nu, sumTo)
}

YY <- function(lam, nu, sumTo) {
    .Call('_convReg_YY', PACKAGE = 'convReg', lam, nu, sumTo)
}

Z <- function(lam, nu, sumTo) {
    .Call('_convReg_Z', PACKAGE = 'convReg', lam, nu, sumTo)
}

#' Zero-inflated Poisson distribution
#' @param y observations
#' @param lam Mean Poisson paramter
#' @param pi Inflation probability
#' @param sumTo integer value for calculating the distribution. Default to 100.
#' @param logP Logical. Should the value be on log scale.
#' @keywords zero inflated Poisson
#' @export
dZIP <- function(y, lam, pi, sumTo = 100L, logP = FALSE) {
    .Call('_convReg_dZIP', PACKAGE = 'convReg', y, lam, pi, sumTo, logP)
}

#' Hurdle Poisson distribution
#' @param y observations
#' @param lam Mean Poisson paramter
#' @param pi Hurdle probability
#' @param logP Logical. Should the value be on log scale.
#' @keywords hurdle Poisson
#' @export
dHP <- function(y, lam, pi, logP = FALSE) {
    .Call('_convReg_dHP', PACKAGE = 'convReg', y, lam, pi, logP)
}

#' Conway Maxwell Poisson distribution
#' @param y observations
#' @param lam Mean Poisson paramter
#' @param nu Variance parameter
#' @param sumTo integer value for calculating the distribution. Default to 50.
#' @param logP Logical. Should the value be on log scale.
#' @keywords Conway Maxwell Poisson
#' @export
dcomp <- function(y, lam, nu, sumTo = 50L, logP = FALSE) {
    .Call('_convReg_dcomp', PACKAGE = 'convReg', y, lam, nu, sumTo, logP)
}

#' Zero-truncated Poisson distribution
#' @param y observations
#' @param lam Mean Poisson paramter
#' @param logP Logical. Should the value be on log scale.
#' @keywords zero truncated Poisson
#' @export
dtpois <- function(y, lam, logP = FALSE) {
    .Call('_convReg_dtpois', PACKAGE = 'convReg', y, lam, logP)
}

#' Binomial Gaussian convolution
#' @param x observations
#' @param prob Binomial probability
#' @param size Binomial size
#' @param mu Gaussian mean
#' @param sigma Gaussian variance
#' @param log Logical. Should the value be on log scale.
#' @keywords Binomial Gaussian convolution
#' @export
dBinomGauss <- function(x, prob, size, mu, sigma, log = FALSE) {
    .Call('_convReg_dBinomGauss', PACKAGE = 'convReg', x, prob, size, mu, sigma, log)
}

#' Binomial Lognormal convolution
#' @param x observations
#' @param prob Binomial probability
#' @param size Binomial size
#' @param mu Log Gaussian mean
#' @param sigma Log Gaussian variance
#' @param log Logical. Should the value be on log scale.
#' @keywords Binomial Log Gaussian convolution
#' @export
dBinomLnorm <- function(x, prob, size, mu, sigma, log = FALSE) {
    .Call('_convReg_dBinomLnorm', PACKAGE = 'convReg', x, prob, size, mu, sigma, log)
}

#' Negative Binomial Gaussian convolution
#' @param x observations
#' @param mu Negative Binomial mean
#' @param size Negative Binomial size
#' @param mug Gaussian mean
#' @param sigmag Gaussian variance
#' @param log Logical. Should the value be on log scale.
#' @keywords Negative Binomial Gaussian convolution
#' @export
dNbinomGauss <- function(x, mu, size, mug, sigmag, log = FALSE) {
    .Call('_convReg_dNbinomGauss', PACKAGE = 'convReg', x, mu, size, mug, sigmag, log)
}

#' Zero inflated Poisson Gaussian convolution
#' @param x observations
#' @param lam ZIP mean
#' @param pi ZIP probability
#' @param mug Gaussian mean
#' @param sigmag Gaussian variance
#' @param log Logical. Should the value be on log scale.
#' @keywords ZIP Gaussian convolution
#' @export
dZIPGauss <- function(x, lam, pi, mug, sigmag, log = FALSE) {
    .Call('_convReg_dZIPGauss', PACKAGE = 'convReg', x, lam, pi, mug, sigmag, log)
}

#' Hurdle Poisson Gaussian convolution
#' @param x observations
#' @param lam Hurdle mean
#' @param pi Hurdle probability
#' @param mug Gaussian mean
#' @param sigmag Gaussian variance
#' @param log Logical. Should the value be on log scale.
#' @keywords ZIP Gaussian convolution
#' @export
dHPGauss <- function(x, lam, pi, mug, sigmag, log = FALSE) {
    .Call('_convReg_dHPGauss', PACKAGE = 'convReg', x, lam, pi, mug, sigmag, log)
}

#' Negative Binomial Log Gaussian convolution
#' @param x observations
#' @param mu Negative Binomial mean
#' @param size Negative Binomial size
#' @param mug Log Gaussian mean
#' @param sigmag Log Gaussian variance
#' @param log Logical. Should the value be on log scale.
#' @keywords Negative Binomial Log Gaussian convolution
#' @export
dNbinomLnorm <- function(x, mu, size, mug, sigmag, log = FALSE) {
    .Call('_convReg_dNbinomLnorm', PACKAGE = 'convReg', x, mu, size, mug, sigmag, log)
}

#' Conway Maxwell Poisson Gaussian convolution
#' @param x observations
#' @param mu CoMP mean
#' @param size CoMP size
#' @param mug Gaussian mean
#' @param sigmag Gaussian variance
#' @param log Logical. Should the value be on log scale.
#' @keywords CoMP Gaussian convolution
#' @export
dCoMPoissonGauss2 <- function(x, mu, size, mug, sigmag, log = FALSE) {
    .Call('_convReg_dCoMPoissonGauss2', PACKAGE = 'convReg', x, mu, size, mug, sigmag, log)
}

#' Poisson Gaussian convolution
#' @param x observations
#' @param lam Poisson mean
#' @param mug Gaussian mean
#' @param sigmag Gaussian variance
#' @param log Logical. Should the value be on log scale.
#' @keywords Poisson Gaussian convolution
#' @export
dPoisGauss <- function(x, lam, mug, sigmag, log = FALSE) {
    .Call('_convReg_dPoisGauss', PACKAGE = 'convReg', x, lam, mug, sigmag, log)
}

#' Poisson Log Gaussian convolution
#' @param x observations
#' @param lam Poisson mean
#' @param mu Log Gaussian mean
#' @param sigma Log Gaussian variance
#' @param log Logical. Should the value be on log scale.
#' @keywords Poisson Log Gaussian convolution
#' @export
dPoisLnorm <- function(x, lam, mu, sigma, log = FALSE) {
    .Call('_convReg_dPoisLnorm', PACKAGE = 'convReg', x, lam, mu, sigma, log)
}

my_dnorm <- function(x, means, sds) {
    .Call('_convReg_my_dnorm', PACKAGE = 'convReg', x, means, sds)
}

dkNbinomGauss <- function(x, mu, size, mug, sigmag, k) {
    .Call('_convReg_dkNbinomGauss', PACKAGE = 'convReg', x, mu, size, mug, sigmag, k)
}

dkNbinomLnorm <- function(x, mu, size, mug, sigmag, k) {
    .Call('_convReg_dkNbinomLnorm', PACKAGE = 'convReg', x, mu, size, mug, sigmag, k)
}

dkBinomGauss <- function(x, size, prob, mug, sigmag) {
    .Call('_convReg_dkBinomGauss', PACKAGE = 'convReg', x, size, prob, mug, sigmag)
}

dkPoisGauss <- function(x, lam, mug, sigmag) {
    .Call('_convReg_dkPoisGauss', PACKAGE = 'convReg', x, lam, mug, sigmag)
}

dkBinomLnorm <- function(x, size, prob, mug, sigmag) {
    .Call('_convReg_dkBinomLnorm', PACKAGE = 'convReg', x, size, prob, mug, sigmag)
}

dkPoisLnorm <- function(x, lam, mug, sigmag) {
    .Call('_convReg_dkPoisLnorm', PACKAGE = 'convReg', x, lam, mug, sigmag)
}

funoptim <- function(thetavar, thetafixed, transforms, Xmu1, Xmu2, Xsigma1, Xsigma2, idxvar, idxfixed) {
    .Call('_convReg_funoptim', PACKAGE = 'convReg', thetavar, thetafixed, transforms, Xmu1, Xmu2, Xsigma1, Xsigma2, idxvar, idxfixed)
}

rcpp_hello_world <- function() {
    .Call('_convReg_rcpp_hello_world', PACKAGE = 'convReg')
}

f01 <- function(x) {
    .Call('_convReg_f01', PACKAGE = 'convReg', x)
}

fpos <- function(x) {
    .Call('_convReg_fpos', PACKAGE = 'convReg', x)
}

fint <- function(x) {
    .Call('_convReg_fint', PACKAGE = 'convReg', x)
}

fid <- function(x) {
    .Call('_convReg_fid', PACKAGE = 'convReg', x)
}

ftransform <- function(x, name) {
    .Call('_convReg_ftransform', PACKAGE = 'convReg', x, name)
}

